#ifndef MODBUS_GLOBAL_H
#define MODBUS_GLOBAL_H

#define MBUS_SENIOR_BIT_MASK	0xFF00
#define MBUS_JUNIOR_BIT_MASK	0x00FF

#define MBUS_BITS_IN_BYTE		8
#define MBUS_BYTES_IN_REG		2

#define MBUS_SENIOR_BIT_SHIFT	8
#define MBUS_JUNIOR_BIT_SHIFT	0

#define MBUS_SENIOR_BIT_INDEX	1
#define MBUS_JUNIOR_BIT_INDEX	0

#endif
